CREATE TABLE `wi_lastnames` (
  `name` varchar(255) NOT NULL,
  `active` varchar(255) NOT NULL default '1'
) TYPE=MyISAM;

INSERT INTO `wi_lastnames` (`name`, `active`) VALUES 
('Binder', '1'),
('Noel', '1'),
('Young', '1'),
('Roux', '1'),
('Allen', '1'),
('Heron', '1'),
('Mansworld', '1'),
('Babbi', '1'),
('Crazys', '1'),
('Linden', '1'),
('Machlam', '1'),
('Notringham', '1'),
('Opus', '1'),
('Hausermann', '1'),
('McLachlan', '1'),
('McKinsey', '1'),
('Pohl', '1'),
('Schwarzenegger', '1'),
('Mueller', '1'),
('Nosemann', '1'),
('Obolus', '1'),
('Himbaer', '1'),
('Nala', '1'),
('Kandee', '1'),
('Bauer', '1'),
('Simons', '1'),
('Raptor', '1'),
('Maek', '1'),
('Huss', '1'),
('Mondial', '1'),
('Moondancer', '1'),
('Sweetheart', '1'),
('Schnuggy', '1'),
('Swindlehurst', '1'),
('Baumeister', '1'),
('Bloomberg', '1'),
('Dredd', '1'),
('Gridlock', '1'),
('Bohlen', '1'),
('Snapper', '1'),
('Tickle', '1'),
('Ewing', '1'),
('Schwinge', '1'),
('Nonsito', '1');
